[[message]]
speed = 6
mode = "fast"
bitstring = """
____________________________________________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
___XXXXXXXXXXXXX____XXXXX__XXX___XXX__XXXXX_XXX_____________XXXX_____XX___XXX___XX_____X
__X_____XXXXXXXXX_______X_X___X_XXXXX_XXXXX_XX_XXXXX_________XXXXXXX_X_XXX_X_____X_____X
_X_______XXXXXXXXX_____X__X___X_XXXXX____XX_X_XXXXXXX_________XXXXX_XX_XXX_X_____XXXX__X
_X_______XXXXXXXXX____X___X___X_XX_XX___XX__X_XXXXXXX_________XXXX_XXX_XXX_X__X__XXX__XX
_X_______XXXXXXXXX___XXX___XXXX_XX_____XXX__X_XXXXXXX_________XXX___XXX____X__XXXXX___XX
_X_______XXXXXXXXX______X_____X_XX_XX____XX_X_XXXXXXX_________XXXXXX_XXXXX_X__X__XXXX__X
_X_______XXXXXXXXX______X_____X_XXXXX_XX_XX_X_XXXXXXX_________XXXXXX_XXXXX_X_____X__X__X
__X_____XXXXXXXXX___X___X_____X_XXXXX_XXXXX_XX_XXXXX_________XXX_XXX_XXXXX_X_____X_____X
___XXXXXXXXXXXXX_____XXX___XXX___XXX___XXX__XXX_____________XXXXX___XXX___XXX___XXX___XX
____________________________________________XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
"""